name: Print Software Versions

on:
  push:
    branches: [main]

jobs:
  PrintClientSoftwareVersions:
    runs-on: ubuntu-latest
    steps:
      - name: Print Operating System (Desktop, Smartphone)
        run: uname -a

      - name: Install React CLI
        run: npm install -g create-react-app

      - name: Print Web Framework (React.js)
        run: npx create-react-app --version

      - name: Print Node.js Version (Client-side environment)
        run: node --version

  PrintServerSoftwareVersions:
    runs-on: ubuntu-latest
    needs: [PrintClientSoftwareVersions]
    steps:
      - name: Print Operating System (Server 1)
        run: uname -a

      - name: Print Node.js Version (Server 1)
        run: node --version

  PrintDatabaseServerVersion:
    runs-on: ubuntu-latest
    needs: [PrintServerSoftwareVersions]
    steps:
      - name: Print Operating System (Server 2)
        run: uname -a

      - name: Print PostgreSQL Version
        run: psql --version
